### ISSUE TITLE
Exception thrown when exiting while the scan button is active

### ISSUE THREAD

**Issue by BullShark** [BullShark/JSpeak#5]
```
Exception in thread "Thread-0" java.lang.NullPointerException
	at jspeak.ClipReader.stopPlayBack(ClipReader.java:80)
	at jspeak.JSpeak$1.run(JSpeak.java:338)
```

**Comment by BullShark** [comment]
Fixed here: https://github.com/BullShark/JSpeak/commit/8dcab2e6756a8379cef16036f956a1df9009088a

Closing...
